server:
  port: 7998

spring:
  application:
    name: consul-consumer-order7998-consul
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname：127.0.0.1
        service-name: ${spring.application.name}