server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh             #路由id，没有固定规则，要求唯一
          #uri: http://localhost:8001    #匹配后提供的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #动态路由
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由
            #- After=2020-09-03T16:47:21.913+08:00[Asia/Shanghai]   当有服务名相同的有一个不能访问，其他的都不能访问了
        - id: payment_routh2             #路由id，没有固定规则，要求唯一
          #uri: http://localhost:8001    #匹配后提供的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #动态路由
          predicates:
            - Path=/payment/lb/**      #断言，路径相匹配的进行路由
            #- After=2020-09-03T16:47:21.913+08:00[Asia/Shanghai]
            #- Cookie=username,caixiaobai  #带cookie username=caixiaobai
            #- Header=X-Request-Id, \d+    #带请求头X-Request-Id，值为整数


eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway-service9527  #主机名显示的修改，自定义主机名
    prefer-ip-address: true   #访问路径可以显示ip地址
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka


