server:
  port: 8011

spring:
  application:
    name: cloud-privoder-hystrix-payment8011

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #单机版
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  #集群版
    #表示是否将自己注册进eureka,默认为true
    register-with-eureka: true
    #是否抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"