server:
  port: 7997

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
#设置feign客户端超时时间（openFeign默认支持ribbon）OpenFeign默认等待一秒钟，超时会报错
ribbon:
  #指的是建立连接后，服务器读取到可用资源的时间
  ReadTimeout: 5000
  #建立连接所用的时间，适用于网络正常的情况下，两端连接所用正常的时间
  ConnectTimeout: 5000

logging:
  level:
  #feign日志以什么级别监控哪个接口
   com.caixiaobai.springcloud.service.PaymentFeignService: debug