server:
  port: 8001

spring:
  application:
    name: cloud-privoder-zipkin-payment8001
  zipkin:
    base-url: http://localhost:9411  #地址不要写错
  sleuth:
    sampler:
      probability: 1
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/springcloud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  #\u914D\u7F6E\u5728\u4F7F\u7528parametertype\u7684\u503C\u65F6\uFF0C\u53EA\u5199\u4E0B\u9762\u8FD9\u4E2A\u5305\u4E0B\u9762\u7684\u5B9E\u4F53\u7C7B\u540D\u79F0\u5C31\u884C\uFF0C\u4E0D\u7528\u5199\u5168\u7C7B\u540D\u4E86
#  type-aliases-package: com.caixiaobai.springcloud.entities

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #\u5355\u673A\u7248
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  #\u96C6\u7FA4\u7248
    #\u8868\u793A\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u8FDBeureka,\u9ED8\u8BA4\u4E3Atrue
    register-with-eureka: true
    #\u662F\u5426\u6293\u53D6\u5DF2\u6709\u7684\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3Atrue\u3002\u5355\u8282\u70B9\u65E0\u6240\u8C13\uFF0C\u96C6\u7FA4\u5FC5\u987B\u8BBE\u7F6E\u4E3Atrue
    fetch-registry: true
  instance:
    instance-id: paymentzipkin8001  #\u4E3B\u673A\u540D\u663E\u793A\u7684\u4FEE\u6539\uFF0C\u81EA\u5B9A\u4E49\u4E3B\u673A\u540D
    prefer-ip-address: true   #\u8BBF\u95EE\u8DEF\u5F84\u53EF\u4EE5\u663E\u793Aip\u5730\u5740



