server:
  port: 3344

spring:
  application:
    name: cloud-config-cneter   #注册进eureka服务的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15913712889/springcloud-config.git   #git仓库地址
          search-paths:  #搜索目录
            - springcloud-config
      lable: master


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
