server:
  port: 8801

spring:
  application:
    name: cloud-stream-privoder
  cloud:
    stream:
      bindings: #服务的整合处理
        output: #这个名称是一个通道名称
          destination: studyExchange #表示要使用的Exchange名称定义
          context-type: application/json  #设置消息类型，本次为json,文本则设置“text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
      binders: #在此处配置绑定的rabbitmq的配置信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment:  #设置rabbit的相关配置环境
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒是的间隔（默认是90秒）
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间，默认是30秒
    instance-id: send-8801.com #z在信息列表显示主机名称
    prefer-ip-address: true #访问的路径变为ip地址